export const TRACK_OPERATING_SEED = [
  {
    code: "01",
    slug: "strategy",
    nameAr: "المسار الاستراتيجي",
    nameEn: "Strategic Path",
    descriptionAr: "التخطيط والتشخيص والتحليل الاستراتيجي وصياغة الاستراتيجية والمواءمة.",
    descriptionEn: "Planning, diagnosis, strategic analysis, strategy formulation, and alignment.",
    purposeAr: "بناء القدرة على صياغة الاتجاه وتحويل الطموح إلى خيارات قابلة للتنفيذ.",
    purposeEn: "Build the ability to set direction and turn ambition into executable choices.",
    scopeAr: "التخطيط، التشخيص، التحليل، الصياغة، والمواءمة الاستراتيجية.",
    scopeEn: "Planning, diagnosis, analysis, formulation, and strategic alignment.",
    iconKey: "strategy",
  },
  {
    code: "02",
    slug: "execution",
    nameAr: "مسار التنفيذ",
    nameEn: "Execution Path",
    descriptionAr: "تحويل الاستراتيجية إلى مبادرات وبرامج وحوكمة تنفيذ وتسليم.",
    descriptionEn: "Translating strategy into initiatives, programs, execution governance, and delivery.",
    purposeAr: "تمكين التنفيذ المنضبط للمبادرات والبرامج.",
    purposeEn: "Enable disciplined delivery of initiatives and programs.",
    scopeAr: "المبادرات، البرامج، حوكمة التنفيذ، والتسليم.",
    scopeEn: "Initiatives, programs, execution governance, and delivery.",
    iconKey: "execution",
  },
  {
    code: "03",
    slug: "performance",
    nameAr: "مسار الأداء",
    nameEn: "Performance Path",
    descriptionAr: "مؤشرات الأداء والقياس والتحليل ولوحات المتابعة وإدارة الانحرافات.",
    descriptionEn: "KPIs, performance measurement, analysis, dashboards, and deviation management.",
    purposeAr: "بناء منظومات أداء قابلة للقياس والتحسين.",
    purposeEn: "Build measurable and improvable performance systems.",
    scopeAr: "المؤشرات، القياس، التحليل، لوحات المتابعة، والانحرافات.",
    scopeEn: "KPIs, measurement, analysis, dashboards, and deviations.",
    iconKey: "performance",
  },
  {
    code: "04",
    slug: "institutional-excellence",
    nameAr: "مسار التميز المؤسسي",
    nameEn: "Institutional Excellence Path",
    descriptionAr: "الجودة والنضج المؤسسي والتحسين المستمر ونماذج التميز.",
    descriptionEn: "Quality, institutional maturity, continuous improvement, and excellence models.",
    purposeAr: "ترسيخ الجودة والتحسين المؤسسي المستمر.",
    purposeEn: "Embed quality and continuous institutional improvement.",
    scopeAr: "الجودة، النضج، التحسين المستمر، ونماذج التميز.",
    scopeEn: "Quality, maturity, continuous improvement, and excellence models.",
    iconKey: "excellence",
  },
  {
    code: "05",
    slug: "institutional-transformation",
    nameAr: "مسار التحول المؤسسي",
    nameEn: "Institutional Transformation Path",
    descriptionAr: "إدارة التغيير والتطوير التنظيمي والابتكار والتحول.",
    descriptionEn: "Change management, organizational development, innovation, and transformation.",
    purposeAr: "قيادة التحول من التصور إلى التبني والاستدامة.",
    purposeEn: "Lead transformation from intent through adoption and continuity.",
    scopeAr: "التغيير، التطوير التنظيمي، الابتكار، والتحول.",
    scopeEn: "Change, OD, innovation, and transformation.",
    iconKey: "transformation",
  },
  {
    code: "06",
    slug: "grc",
    nameAr: "مسار الحوكمة والمخاطر",
    nameEn: "Governance, Risk & Compliance Path",
    descriptionAr: "الحوكمة والمخاطر والامتثال والرقابة الداخلية والسياسات وصناعة القرار.",
    descriptionEn: "Governance, risk, compliance, internal controls, policies, and decision-making.",
    purposeAr: "تعزيز القرار المسؤول والمرونة والامتثال.",
    purposeEn: "Strengthen responsible decisions, resilience, and compliance.",
    scopeAr: "الحوكمة، المخاطر، الامتثال، الرقابة، والسياسات.",
    scopeEn: "Governance, risk, compliance, controls, and policies.",
    iconKey: "grc",
  },
  {
    code: "07",
    slug: "human-capital",
    nameAr: "مسار رأس المال البشري",
    nameEn: "Human Capital Path",
    descriptionAr: "استراتيجية القوى العاملة والقيادة والثقافة المؤسسية وتطوير القدرات وتجربة الموظف.",
    descriptionEn: "Workforce strategy, leadership, organizational culture, capability development, and employee experience.",
    purposeAr: "تمكين القدرات والثقافة والقيادات المؤسسية.",
    purposeEn: "Enable institutional capability, culture, and leadership.",
    scopeAr: "القوى العاملة، القيادة، الثقافة، القدرات، وتجربة الموظف.",
    scopeEn: "Workforce, leadership, culture, capability, and employee experience.",
    iconKey: "human-capital",
  },
  {
    code: "08",
    slug: "ai-automation",
    nameAr: "مسار الذكاء الاصطناعي والأتمتة",
    nameEn: "AI & Automation Path",
    descriptionAr: "استراتيجية الذكاء الاصطناعي وجاهزية البيانات والمساعدات الذكية وأنظمة المعرفة وأتمتة سير العمل واكتشاف العمليات والذكاء الاصطناعي المسؤول والحوكمة والتبني وتحسين الإنتاجية.",
    descriptionEn: "AI strategy, data readiness, intelligent assistants, RAG and knowledge systems, workflow automation, process discovery, responsible AI, governance, adoption, and measurable productivity improvement.",
    purposeAr: "توظيف التقنية لصناعة قيمة عملية قابلة للقياس.",
    purposeEn: "Apply technology to create practical, measurable value.",
    scopeAr: "استراتيجية الذكاء الاصطناعي، البيانات، الأتمتة، والحوكمة المسؤولة.",
    scopeEn: "AI strategy, data, automation, and responsible governance.",
    iconKey: "ai-automation",
  },
] as const;

export const TRACK_CONTRIBUTION_TYPES = [
  { slug: "article", nameAr: "مقالات وموارد معرفية", nameEn: "Articles and knowledge resources" },
  { slug: "template", nameAr: "قوالب وأدوات مهنية", nameEn: "Templates and professional tools" },
  { slug: "workshop", nameAr: "ورش ودورات تدريبية", nameEn: "Workshops and training sessions" },
  { slug: "consultation", nameAr: "استشارات وإرشاد", nameEn: "Consultations and mentoring" },
  { slug: "assessment", nameAr: "تقييمات وأدوات تشخيص", nameEn: "Assessments and diagnostic tools" },
  { slug: "initiative", nameAr: "مبادرات ومشاريع تنفيذ", nameEn: "Initiatives and implementation projects" },
  { slug: "research", nameAr: "بحوث ودراسات حالة", nameEn: "Research and case studies" },
  { slug: "volunteer_task", nameAr: "مهام تطوعية", nameEn: "Volunteer tasks" },
  { slug: "ai_automation", nameAr: "أتمتة وذكاء اصطناعي قابل لإعادة الاستخدام", nameEn: "AI automations and reusable workflows" },
  { slug: "event", nameAr: "فعاليات وجلسات عمل", nameEn: "Events and working sessions" },
] as const;

export const TRACK_MEMBER_ROLES = [
  "member",
  "expert",
  "founder",
  "volunteer",
  "reviewer",
  "mentor",
] as const;

export const TRACK_LEADERSHIP_ROLES = ["primary", "deputy"] as const;

export const TRACK_APPLICATION_STATUSES = [
  "submitted",
  "under_review",
  "approved",
  "rejected",
  "withdrawn",
] as const;

export const TRACK_CONTRIBUTION_STATUSES = [
  "draft",
  "submitted",
  "under_review",
  "changes_requested",
  "approved",
  "published",
  "completed",
  "rejected",
  "archived",
  "cancelled",
] as const;

export const TRACK_BADGE_SEEDS = [
  {
    slug: "track_group_leader",
    nameAr: "قائد المسار",
    nameEn: "Group Leader",
    criteriaAr: "تعيين قائد أساسي نشط لمسار مهني",
    criteriaEn: "Active primary leadership assignment for a professional track",
    issuanceMode: "automatic" as const,
    criteria: { trackLeadership: "primary" },
  },
  {
    slug: "track_primary_member",
    nameAr: "المسار الأساسي",
    nameEn: "Primary Track",
    criteriaAr: "عضوية نشطة في المسار الأساسي للعضو",
    criteriaEn: "Active membership in the member's primary track",
    issuanceMode: "automatic" as const,
    criteria: { trackMembership: "primary" },
  },
] as const;
