-- Idempotent seed of the eight official operating tracks (safe on existing production DBs).
INSERT INTO "tracks" (
  "id",
  "code",
  "slug",
  "name_ar",
  "name_en",
  "description_ar",
  "description_en",
  "purpose_ar",
  "purpose_en",
  "scope_ar",
  "scope_en",
  "icon_key",
  "status",
  "is_enabled",
  "applications_open",
  "allow_secondary",
  "max_secondary",
  "sort_order",
  "created_at",
  "updated_at"
) VALUES
  (
    '01999990-0001-7000-8000-000000000001',
    '01',
    'strategy',
    'المسار الاستراتيجي',
    'Strategic Path',
    'التخطيط والتشخيص والتحليل الاستراتيجي وصياغة الاستراتيجية والمواءمة.',
    'Planning, diagnosis, strategic analysis, strategy formulation, and alignment.',
    'بناء القدرة على صياغة الاتجاه وتحويل الطموح إلى خيارات قابلة للتنفيذ.',
    'Build the ability to set direction and turn ambition into executable choices.',
    'التخطيط، التشخيص، التحليل، الصياغة، والمواءمة الاستراتيجية.',
    'Planning, diagnosis, analysis, formulation, and strategic alignment.',
    'strategy',
    'active',
    true,
    true,
    true,
    2,
    1,
    now(),
    now()
  ),
  (
    '01999990-0001-7000-8000-000000000002',
    '02',
    'execution',
    'مسار التنفيذ',
    'Execution Path',
    'تحويل الاستراتيجية إلى مبادرات وبرامج وحوكمة تنفيذ وتسليم.',
    'Translating strategy into initiatives, programs, execution governance, and delivery.',
    'تمكين التنفيذ المنضبط للمبادرات والبرامج.',
    'Enable disciplined delivery of initiatives and programs.',
    'المبادرات، البرامج، حوكمة التنفيذ، والتسليم.',
    'Initiatives, programs, execution governance, and delivery.',
    'execution',
    'active',
    true,
    true,
    true,
    2,
    2,
    now(),
    now()
  ),
  (
    '01999990-0001-7000-8000-000000000003',
    '03',
    'performance',
    'مسار الأداء',
    'Performance Path',
    'مؤشرات الأداء والقياس والتحليل ولوحات المتابعة وإدارة الانحرافات.',
    'KPIs, performance measurement, analysis, dashboards, and deviation management.',
    'بناء منظومات أداء قابلة للقياس والتحسين.',
    'Build measurable and improvable performance systems.',
    'المؤشرات، القياس، التحليل، لوحات المتابعة، والانحرافات.',
    'KPIs, measurement, analysis, dashboards, and deviations.',
    'performance',
    'active',
    true,
    true,
    true,
    2,
    3,
    now(),
    now()
  ),
  (
    '01999990-0001-7000-8000-000000000004',
    '04',
    'institutional-excellence',
    'مسار التميز المؤسسي',
    'Institutional Excellence Path',
    'الجودة والنضج المؤسسي والتحسين المستمر ونماذج التميز.',
    'Quality, institutional maturity, continuous improvement, and excellence models.',
    'ترسيخ الجودة والتحسين المؤسسي المستمر.',
    'Embed quality and continuous institutional improvement.',
    'الجودة، النضج، التحسين المستمر، ونماذج التميز.',
    'Quality, maturity, continuous improvement, and excellence models.',
    'excellence',
    'active',
    true,
    true,
    true,
    2,
    4,
    now(),
    now()
  ),
  (
    '01999990-0001-7000-8000-000000000005',
    '05',
    'institutional-transformation',
    'مسار التحول المؤسسي',
    'Institutional Transformation Path',
    'إدارة التغيير والتطوير التنظيمي والابتكار والتحول.',
    'Change management, organizational development, innovation, and transformation.',
    'قيادة التحول من التصور إلى التبني والاستدامة.',
    'Lead transformation from intent through adoption and continuity.',
    'التغيير، التطوير التنظيمي، الابتكار، والتحول.',
    'Change, OD, innovation, and transformation.',
    'transformation',
    'active',
    true,
    true,
    true,
    2,
    5,
    now(),
    now()
  ),
  (
    '01999990-0001-7000-8000-000000000006',
    '06',
    'grc',
    'مسار الحوكمة والمخاطر',
    'Governance, Risk & Compliance Path',
    'الحوكمة والمخاطر والامتثال والرقابة الداخلية والسياسات وصناعة القرار.',
    'Governance, risk, compliance, internal controls, policies, and decision-making.',
    'تعزيز القرار المسؤول والمرونة والامتثال.',
    'Strengthen responsible decisions, resilience, and compliance.',
    'الحوكمة، المخاطر، الامتثال، الرقابة، والسياسات.',
    'Governance, risk, compliance, controls, and policies.',
    'grc',
    'active',
    true,
    true,
    true,
    2,
    6,
    now(),
    now()
  ),
  (
    '01999990-0001-7000-8000-000000000007',
    '07',
    'human-capital',
    'مسار رأس المال البشري',
    'Human Capital Path',
    'استراتيجية القوى العاملة والقيادة والثقافة المؤسسية وتطوير القدرات وتجربة الموظف.',
    'Workforce strategy, leadership, organizational culture, capability development, and employee experience.',
    'تمكين القدرات والثقافة والقيادات المؤسسية.',
    'Enable institutional capability, culture, and leadership.',
    'القوى العاملة، القيادة، الثقافة، القدرات، وتجربة الموظف.',
    'Workforce, leadership, culture, capability, and employee experience.',
    'human-capital',
    'active',
    true,
    true,
    true,
    2,
    7,
    now(),
    now()
  ),
  (
    '01999990-0001-7000-8000-000000000008',
    '08',
    'ai-automation',
    'مسار الذكاء الاصطناعي والأتمتة',
    'AI & Automation Path',
    'استراتيجية الذكاء الاصطناعي وجاهزية البيانات والمساعدات الذكية وأنظمة المعرفة وأتمتة سير العمل واكتشاف العمليات والذكاء الاصطناعي المسؤول والحوكمة والتبني وتحسين الإنتاجية.',
    'AI strategy, data readiness, intelligent assistants, RAG and knowledge systems, workflow automation, process discovery, responsible AI, governance, adoption, and measurable productivity improvement.',
    'توظيف التقنية لصناعة قيمة عملية قابلة للقياس.',
    'Apply technology to create practical, measurable value.',
    'استراتيجية الذكاء الاصطناعي، البيانات، الأتمتة، والحوكمة المسؤولة.',
    'AI strategy, data, automation, and responsible governance.',
    'ai-automation',
    'active',
    true,
    true,
    true,
    2,
    8,
    now(),
    now()
  )
ON CONFLICT ("slug") DO UPDATE SET
  "code" = EXCLUDED."code",
  "name_ar" = EXCLUDED."name_ar",
  "name_en" = EXCLUDED."name_en",
  "description_ar" = EXCLUDED."description_ar",
  "description_en" = EXCLUDED."description_en",
  "purpose_ar" = EXCLUDED."purpose_ar",
  "purpose_en" = EXCLUDED."purpose_en",
  "scope_ar" = EXCLUDED."scope_ar",
  "scope_en" = EXCLUDED."scope_en",
  "icon_key" = EXCLUDED."icon_key",
  "status" = CASE WHEN "tracks"."status" = 'archived' THEN "tracks"."status" ELSE 'active' END,
  "is_enabled" = true,
  "applications_open" = COALESCE("tracks"."applications_open", true),
  "allow_secondary" = COALESCE("tracks"."allow_secondary", true),
  "max_secondary" = COALESCE("tracks"."max_secondary", 2),
  "sort_order" = EXCLUDED."sort_order",
  "updated_at" = now();
