-- Seed membership types with stable UUIDs and correct configuration
-- Idempotent with INSERT ... ON CONFLICT (slug) DO NOTHING
-- Covers all 9 membership types with appropriate application settings

INSERT INTO "membership_types" (
  "id",
  "slug",
  "code",
  "name_ar",
  "name_en",
  "description_ar",
  "description_en",
  "is_enabled",
  "applications_open",
  "invitation_only",
  "visibility",
  "validity_mode",
  "sort_order",
  "created_at",
  "updated_at"
) VALUES
-- Open Applications
(
  '550e8400-e29b-41d4-a716-446655440001',
  'founding_member',
  'FND',
  'عضو مؤسس',
  'Founding Member',
  'عضو من المؤسسين الأصليين',
  'Original founding member',
  true,
  false,
  true,
  'public',
  'lifetime',
  5,
  now(),
  now()
),
(
  '550e8400-e29b-41d4-a716-446655440002',
  'expert_member',
  'EXP',
  'عضو خبير',
  'Expert Member',
  'خبير متخصص في مجال من مجالات العمل',
  'Specialized expert in a field of work',
  true,
  true,
  false,
  'public',
  'lifetime',
  10,
  now(),
  now()
),
(
  '550e8400-e29b-41d4-a716-446655440003',
  'professional_member',
  'PRO',
  'عضو متخصص',
  'Professional Member',
  'متخصص في مجال من مجالات العمل',
  'Professional in a field of work',
  true,
  true,
  false,
  'public',
  'lifetime',
  20,
  now(),
  now()
),
(
  '550e8400-e29b-41d4-a716-446655440004',
  'contributor',
  'CTR',
  'مساهم',
  'Contributor',
  'شخص يساهم في مشاريع العيادة',
  'Person contributing to clinic projects',
  true,
  true,
  false,
  'public',
  'lifetime',
  30,
  now(),
  now()
),
(
  '550e8400-e29b-41d4-a716-446655440005',
  'volunteer_member',
  'VOL',
  'عضو متطوع',
  'Volunteer Member',
  'متطوع منتظم في برامج العيادة',
  'Regular volunteer in clinic programs',
  true,
  true,
  false,
  'public',
  'lifetime',
  40,
  now(),
  now()
),
(
  '550e8400-e29b-41d4-a716-446655440006',
  'volunteer_leader',
  'VLD',
  'قائد فريق متطوع',
  'Volunteer Leader',
  'قائد فريق متطوعين في البرامج',
  'Team leader of volunteer programs',
  true,
  true,
  false,
  'public',
  'lifetime',
  50,
  now(),
  now()
),
(
  '550e8400-e29b-41d4-a716-446655440007',
  'distinguished_volunteer',
  'DVL',
  'متطوع متميز',
  'Distinguished Volunteer',
  'متطوع متميز بإسهامات استثنائية',
  'Distinguished volunteer with exceptional contributions',
  true,
  true,
  false,
  'public',
  'lifetime',
  60,
  now(),
  now()
),
-- Invitation-only (closed applications)
(
  '550e8400-e29b-41d4-a716-446655440008',
  'strategic_partner',
  'PTR',
  'شريك استراتيجي',
  'Strategic Partner',
  'شريك استراتيجي للعيادة',
  'Strategic partner of the clinic',
  true,
  false,
  true,
  'public',
  'lifetime',
  15,
  now(),
  now()
),
(
  '550e8400-e29b-41d4-a716-446655440009',
  'institutional_member',
  'INS',
  'عضو مؤسسة',
  'Institutional Member',
  'عضو من مؤسسة شريكة',
  'Member from partner institution',
  true,
  false,
  true,
  'public',
  'lifetime',
  25,
  now(),
  now()
)
ON CONFLICT ("slug") DO NOTHING;

