export const PERMISSIONS = [
  "identity.session.revoke_any",
  "identity.user.disable",
  "rbac.role.grant",
  "rbac.role.read",
  "security.settings.write",
  "security.events.read",
  "membership.type.read",
  "membership.type.manage",
  "membership.track.read",
  "membership.track.manage",
  "membership.application.create",
  "membership.application.read.own",
  "membership.application.withdraw.own",
  "membership.application.read.any",
  "membership.application.review",
  "membership.application.assign",
  "membership.application.approve",
  "membership.application.reject",
  "membership.read.own",
  "membership.read.any",
  "membership.issue",
  "membership.suspend",
  "membership.revoke",
  "credential.read.own",
  "credential.read.any",
  "credential.issue",
  "credential.suspend",
  "credential.revoke",
  "credential.asset.generate",
  "credential.audit.read",
  "credential.render",
  "volunteer.profile.read.own",
  "volunteer.profile.update.own",
  "volunteer.profile.read.any",
  "volunteer.opportunity.read",
  "volunteer.opportunity.create",
  "volunteer.opportunity.update",
  "volunteer.opportunity.manage",
  "volunteer.application.create",
  "volunteer.application.read.own",
  "volunteer.application.withdraw.own",
  "volunteer.application.read.any",
  "volunteer.application.review",
  "volunteer.application.accept",
  "volunteer.application.reject",
  "volunteer.participation.read.own",
  "volunteer.participation.read.any",
  "volunteer.participation.manage",
  "volunteer.attendance.record",
  "volunteer.hours.create.own",
  "volunteer.hours.read.own",
  "volunteer.hours.read.any",
  "volunteer.hours.review",
  "volunteer.hours.adjust",
  "volunteer.progression.read",
  "volunteer.progression.manage",
  "volunteer.impact.read.own",
  "volunteer.impact.read.any",
  "contribution.create.own",
  "contribution.read.own",
  "contribution.read.any",
  "contribution.review",
  "contribution.approve",
  "contribution.reject",
  "contribution.revoke",
  "badge.read.own",
  "badge.read.any",
  "badge.definition.manage",
  "badge.issue",
  "badge.revoke",
  "certificate.read.own",
  "certificate.read.any",
  "certificate.definition.manage",
  "certificate.issue",
  "certificate.revoke",
  "impact.read.own",
  "impact.read.any",
  "impact.config.manage",
  "milestone.config.manage",
  "directory.profile.manage.own",
  "badge.definition.write",
  "badge.award.issue",
  "badge.award.revoke",
  "content.write",
  "content.read",
  "announcement.manage",
  "settings.manage",
  "notification.read.own",
  "notification.manage.own",
  "notification.ops.read",
  "notification.ops.manage",
  "analytics.read",
  "partner.write",
  "admin.dashboard.read",
  "audit.read",
  "flag.write",
  "report.read",
  "track.read",
  "track.manage",
  "track.application.create",
  "track.application.read.own",
  "track.application.withdraw.own",
  "track.application.read.any",
  "track.application.review",
  "track.application.approve",
  "track.application.reject",
  "track.membership.read.own",
  "track.membership.read.scoped",
  "track.membership.assign",
  "track.leadership.manage",
  "track.contribution.create.own",
  "track.contribution.read.own",
  "track.contribution.read.scoped",
  "track.contribution.review",
  "track.contribution.approve",
  "track.initiative.manage",
  "track.task.manage",
  "track.event.manage",
  "track.analytics.read",
  "track.announcement.manage",
  "consultation.create",
  "consultation.read.own",
  "consultation.read.assigned",
  "consultation.read.any",
  "consultation.assign",
  "consultation.respond",
  "consultation.manage",
  "meeting.read.own",
  "meeting.create",
  "meeting.manage",
  "meeting.start",
  "credential.template.manage",
  "admin.settings.manage",
  "membership.manage",
  "volunteer.manage",
  "card.read.own",
  "card.template.manage",
  "track.member.manage",
  "support.request.create",
  "support.request.read.any",
] as const;

export type Permission = (typeof PERMISSIONS)[number];

export const ROLE_SEEDS = [
  { slug: "super_admin", nameAr: "مدير أعلى", nameEn: "Super Admin" },
  { slug: "platform_admin", nameAr: "مدير المنصة", nameEn: "Platform Admin" },
  { slug: "membership_admin", nameAr: "مدير العضوية", nameEn: "Membership Admin" },
  { slug: "volunteer_admin", nameAr: "مدير التطوع", nameEn: "Volunteer Admin" },
  { slug: "track_lead", nameAr: "قائد مسار", nameEn: "Track Lead" },
  { slug: "volunteer_leader", nameAr: "قائد متطوعين", nameEn: "Volunteer Leader" },
  { slug: "reviewer", nameAr: "مراجع", nameEn: "Reviewer" },
  { slug: "content_manager", nameAr: "مدير محتوى", nameEn: "Content Manager" },
  { slug: "partner_manager", nameAr: "مدير الشراكات", nameEn: "Partner Manager" },
  { slug: "auditor", nameAr: "مدقق", nameEn: "Auditor" },
  { slug: "expert", nameAr: "خبير", nameEn: "Expert" },
  { slug: "founder", nameAr: "مؤسس", nameEn: "Founder" },
  { slug: "volunteer", nameAr: "متطوع", nameEn: "Volunteer" },
  { slug: "member", nameAr: "عضو", nameEn: "Member" },
] as const;

export type RoleSlug = (typeof ROLE_SEEDS)[number]["slug"];

const ALL = [...PERMISSIONS];

const MEMBERSHIP_ADMIN_PERMS = [
  "membership.type.read",
  "membership.type.manage",
  "membership.track.read",
  "membership.track.manage",
  "membership.application.read.any",
  "membership.application.review",
  "membership.application.assign",
  "membership.application.approve",
  "membership.application.reject",
  "membership.read.any",
  "membership.issue",
  "membership.suspend",
  "membership.revoke",
  "membership.manage",
  "admin.dashboard.read",
] as const satisfies readonly Permission[];

const VOLUNTEER_ADMIN_PERMS = [
  "volunteer.profile.read.any",
  "volunteer.opportunity.read",
  "volunteer.opportunity.create",
  "volunteer.opportunity.update",
  "volunteer.opportunity.manage",
  "volunteer.application.read.any",
  "volunteer.application.review",
  "volunteer.application.accept",
  "volunteer.application.reject",
  "volunteer.participation.read.any",
  "volunteer.participation.manage",
  "volunteer.attendance.record",
  "volunteer.hours.read.any",
  "volunteer.hours.review",
  "volunteer.hours.adjust",
  "volunteer.progression.read",
  "volunteer.progression.manage",
  "volunteer.impact.read.any",
  "volunteer.manage",
  "admin.dashboard.read",
] as const satisfies readonly Permission[];

const VOLUNTEER_LEADER_PERMS = [
  "volunteer.opportunity.read",
  "volunteer.opportunity.create",
  "volunteer.opportunity.update",
  "volunteer.opportunity.manage",
  "volunteer.application.read.any",
  "volunteer.application.review",
  "volunteer.participation.read.any",
  "volunteer.participation.manage",
  "volunteer.attendance.record",
  "volunteer.hours.read.any",
  "volunteer.hours.review",
] as const satisfies readonly Permission[];

const MEMBER_VOLUNTEER_PERMS = [
  "volunteer.profile.read.own",
  "volunteer.profile.update.own",
  "volunteer.opportunity.read",
  "volunteer.application.create",
  "volunteer.application.read.own",
  "volunteer.application.withdraw.own",
  "volunteer.participation.read.own",
  "volunteer.hours.create.own",
  "volunteer.hours.read.own",
  "volunteer.progression.read",
  "volunteer.impact.read.own",
] as const satisfies readonly Permission[];

const RECOGNITION_ADMIN_PERMS = [
  "contribution.read.any",
  "contribution.review",
  "contribution.approve",
  "contribution.reject",
  "contribution.revoke",
  "badge.read.any",
  "badge.definition.manage",
  "badge.issue",
  "badge.revoke",
  "certificate.read.any",
  "certificate.definition.manage",
  "certificate.issue",
  "certificate.revoke",
  "impact.read.any",
  "impact.config.manage",
  "milestone.config.manage",
  "badge.definition.write",
  "badge.award.issue",
  "badge.award.revoke",
] as const satisfies readonly Permission[];

const MEMBER_RECOGNITION_PERMS = [
  "contribution.create.own",
  "contribution.read.own",
  "badge.read.own",
  "certificate.read.own",
  "impact.read.own",
  "directory.profile.manage.own",
  "notification.read.own",
  "notification.manage.own",
] as const satisfies readonly Permission[];

const TRACK_ADMIN_PERMS = [
  "track.read",
  "track.manage",
  "track.application.read.any",
  "track.application.review",
  "track.application.approve",
  "track.application.reject",
  "track.membership.read.scoped",
  "track.membership.assign",
  "track.leadership.manage",
  "track.contribution.read.scoped",
  "track.contribution.review",
  "track.contribution.approve",
  "track.initiative.manage",
  "track.task.manage",
  "track.event.manage",
  "track.analytics.read",
  "track.announcement.manage",
  "track.member.manage",
] as const satisfies readonly Permission[];

const TRACK_LEADER_PERMS = [
  "track.read",
  "track.application.read.any",
  "track.application.review",
  "track.application.approve",
  "track.application.reject",
  "track.membership.read.scoped",
  "track.contribution.read.scoped",
  "track.contribution.review",
  "track.contribution.approve",
  "track.initiative.manage",
  "track.task.manage",
  "track.event.manage",
  "track.analytics.read",
  "track.announcement.manage",
  "track.member.manage",
  "volunteer.hours.review",
  "meeting.start",
] as const satisfies readonly Permission[];

const MEMBER_TRACK_PERMS = [
  "track.read",
  "track.application.create",
  "track.application.read.own",
  "track.application.withdraw.own",
  "track.membership.read.own",
  "track.contribution.create.own",
  "track.contribution.read.own",
] as const satisfies readonly Permission[];

const OPS_ADMIN_PERMS = [
  "admin.dashboard.read",
  "analytics.read",
  "audit.read",
  "security.events.read",
  "settings.manage",
  "admin.settings.manage",
  "notification.ops.read",
  "notification.ops.manage",
  "announcement.manage",
  "content.write",
  "content.read",
  "support.request.read.any",
  "flag.write",
  "report.read",
] as const satisfies readonly Permission[];

const CONSULTATION_ADMIN_PERMS = [
  "consultation.read.any",
  "consultation.assign",
  "consultation.respond",
  "consultation.manage",
  "meeting.read.own",
  "meeting.create",
  "meeting.manage",
  "meeting.start",
] as const satisfies readonly Permission[];

export const ROLE_PERMISSION_MAP: Record<RoleSlug, readonly Permission[]> = {
  super_admin: ALL,
  platform_admin: [
    "identity.user.disable",
    "rbac.role.read",
    "security.events.read",
    ...MEMBERSHIP_ADMIN_PERMS,
    "credential.read.any",
    "credential.issue",
    "credential.suspend",
    "credential.revoke",
    "credential.asset.generate",
    "credential.audit.read",
    "credential.render",
    "credential.revoke",
    ...VOLUNTEER_ADMIN_PERMS,
    ...RECOGNITION_ADMIN_PERMS,
    ...TRACK_ADMIN_PERMS,
    ...CONSULTATION_ADMIN_PERMS,
    "credential.template.manage",
    "card.template.manage",
    ...OPS_ADMIN_PERMS,
  ],
  membership_admin: [
    ...MEMBERSHIP_ADMIN_PERMS,
    ...TRACK_ADMIN_PERMS,
    "credential.read.any",
    "credential.issue",
    "credential.suspend",
    "credential.revoke",
    "credential.template.manage",
    "card.template.manage",
    "credential.asset.generate",
    "credential.audit.read",
    "credential.render",
    "credential.revoke",
  ],
  volunteer_admin: [...VOLUNTEER_ADMIN_PERMS, "badge.award.issue", "badge.issue"],
  track_lead: [
    "membership.type.read",
    "membership.track.read",
    ...TRACK_LEADER_PERMS,
    "consultation.read.assigned",
    "consultation.respond",
    "meeting.read.own",
    "meeting.create",
    "meeting.start",
    "track.member.manage",
  ],
  volunteer_leader: VOLUNTEER_LEADER_PERMS,
  reviewer: [
    "membership.type.read",
    "membership.track.read",
    "membership.application.read.any",
    "membership.application.review",
    "membership.application.approve",
    "membership.application.reject",
    "volunteer.hours.review",
    "volunteer.application.review",
    "contribution.read.any",
    "contribution.review",
    "contribution.approve",
    "contribution.reject",
    "track.contribution.read.scoped",
    "track.contribution.review",
    "consultation.read.assigned",
    "consultation.respond",
    "meeting.read.own",
  ],
  content_manager: [
    "admin.dashboard.read",
    "content.write",
    "content.read",
    "announcement.manage",
  ],
  partner_manager: ["partner.write"],
  expert: [
    "membership.type.read",
    "membership.track.read",
    "membership.read.own",
    "credential.read.own",
    "card.read.own",
    "track.read",
    "consultation.read.own",
    "consultation.read.assigned",
    "consultation.respond",
    "meeting.read.own",
    "meeting.create",
    "meeting.start",
    "support.request.create",
  ],
  founder: [
    "membership.type.read",
    "membership.track.read",
    "membership.application.create",
    "membership.application.read.own",
    "membership.application.withdraw.own",
    "membership.read.own",
    "credential.read.own",
    "card.read.own",
    ...MEMBER_TRACK_PERMS,
    ...MEMBER_RECOGNITION_PERMS,
    "consultation.create",
    "consultation.read.own",
    "meeting.read.own",
    "support.request.create",
  ],
  volunteer: [
    "membership.read.own",
    "credential.read.own",
    "card.read.own",
    ...MEMBER_VOLUNTEER_PERMS,
    "contribution.create.own",
    "contribution.read.own",
    "badge.read.own",
    "certificate.read.own",
    "notification.read.own",
    "notification.manage.own",
    "support.request.create",
  ],
  auditor: [
    "rbac.role.read",
    "security.events.read",
    "admin.dashboard.read",
    "audit.read",
    "report.read",
    "membership.read.any",
    "membership.application.read.any",
    "contribution.read.any",
    "badge.read.any",
    "certificate.read.any",
    "impact.read.any",
    "track.read",
    "track.analytics.read",
  ],
  member: [
    "membership.type.read",
    "membership.track.read",
    "membership.application.create",
    "membership.application.read.own",
    "membership.application.withdraw.own",
    "membership.read.own",
    "credential.read.own",
    "credential.asset.generate",
    ...MEMBER_VOLUNTEER_PERMS,
    ...MEMBER_RECOGNITION_PERMS,
    ...MEMBER_TRACK_PERMS,
    "consultation.create",
    "consultation.read.own",
    "meeting.read.own",
    "card.read.own",
    "support.request.create",
  ],
};
